#!/bin/bash
# vim: et sr sw=4 ts=4 smartindent:
#
# create_eurostar_service_info.sh
#
# Will generate a file under /etc/eurostar/eurostar_service_info
# This file contains key=value pairs that can be sourced in to a 
# bash script etc ...
#
# It contains stuff that is useful to determine the name and type of this
# service amongst other things.
#
# TODO: Rename service to 'product' to meet naming convention
#
REQUIRED_VARS="
    EUROSTAR_SERVICE_NAME
    EUROSTAR_SERVICE_ROLE
    EUROSTAR_RELEASE_VERSION
"

INFO_FILE="/etc/eurostar/eurostar_service_info"
FAILED_VALIDATION=''
TIMESTAMP="$(date +'%Y-%m-%d %H:%M:%S')"
MARKER="EUROSTAR_SERVICE_INFO GENERATED BY"
OUTPUT_STR="# [$TIMESTAMP] $MARKER $0"

function check_var_defined() {
    var_name="$1"
    var_val="${!var_name}"
    if [[ -z $var_val ]]; then
        echo "$0 ERROR: You must pass \$$var_name to this script" >&2
        FAILED_VALIDATION="you bet'cha"
        return 1
    fi
}

function check_valid_val() {
    var_name="$1"
    var_val="${!var_name}"
    if [[ $var_val =~ [^_a-zA-Z0-9] ]]; then
        echo "$0 ERROR: ILLEGAL CHAR in $var_name val: $var_val" >&2
        echo "$0 ERROR: ... only use alphanumerics or underscore in the value"
        FAILED_VALIDATION="you bet'cha"
        return 1
    fi
}

function add_to_info_str() {
    var_name="$1"
    var_val="${!var_name}"
    key_val="$var_name=$var_val"
    OUTPUT_STR="$OUTPUT_STR\n$key_val"
}

if [[ $EUROSTAR_RELEASE_VERSION =~ \. ]]; then
    echo "$0 INFO: \$EUROSTAR_RELEASE_VERSION val ${!var_name} contains dots."
    echo "$0 INFO: ... changing dots to underscores for safe app consumption."
    # ... check out the crazy bash variable expansion below ... also works in ash
    EUROSTAR_RELEASE_VERSION=${EUROSTAR_RELEASE_VERSION//\./_}
fi

for this_var in $REQUIRED_VARS; do
    check_var_defined $this_var  \
    && check_valid_val $this_var \
    && add_to_info_str $this_var
done

if [[ ! -z $FAILED_VALIDATION ]]; then
    echo "$0 EXIT: FAILURE. One of more required vars not passed to this script."
    exit 1
fi

mkdir -p $(dirname $INFO_FILE) 2>/dev/null

# ... replace any existing values
if [[ -f $INFO_FILE ]]; then
    sed -i "/$MARKER/,/END $MARKER/d" $INFO_FILE
fi

OUTPUT_STR="$OUTPUT_STR\n# END $MARKER $0"
echo -e "$OUTPUT_STR\n" >>$INFO_FILE

